Repository gantry-project/gantry-docker, pull requests merged in 2023-04, with the labels that each got.

#49 Task 047 apply spring security
  api-server/build.gradle
  api-server/src/main/java/org/gantry/apiserver/ApiServerApplication.java
  api-server/src/main/java/org/gantry/apiserver/config/DockerConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/config/security/InvalidTokenException.java
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTAuthenticationFilter.java
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTAuthorizationFilter.java
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTProperties.java
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTUtil.java
  api-server/src/main/java/org/gantry/apiserver/config/security/SecurityConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/config/security/SimpleSecurityConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/domain/Authority.java
  api-server/src/main/java/org/gantry/apiserver/domain/User.java
  api-server/src/main/java/org/gantry/apiserver/persistence/UserRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/UserService.java
  api-server/src/main/java/org/gantry/apiserver/web/ApplicationController.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/UserDto.java
  api-server/src/main/resources/META-INF/spring-configuration-metadata.json
  api-server/src/main/resources/application.properties
  api-server/src/main/resources/init/data.sql
  api-server/src/test/java/org/gantry/apiserver/config/security/JWTUtilTest.java
  api-server/src/test/java/org/gantry/apiserver/persistence/ApplicationRepositoryTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ApplicationControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/HealthCheckControllerTest.java
Labels: task

#51 Task 050 container status remove from db
  api-server/src/main/java/org/gantry/apiserver/domain/Container.java
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClientConnect.java
  front/eslintrc.js
  front/src/components/DockerList/DockerCat.tsx
  front/src/components/DockerList/DockerItemCard.tsx
  front/src/components/DockerList/DockerListHeader.tsx
  front/src/components/Footer.tsx
  front/src/components/HomeMenu/HomeMenu.tsx
  front/src/components/HomeMenu/HomeMenuCard.tsx
  front/src/components/Layout.tsx
  front/src/components/Navbar.tsx
  front/src/components/UserProfile/UserOrder.tsx
  front/src/dummyData.js
  front/src/pages/ContainerDetail.tsx
  front/src/pages/DockerList.tsx
  front/src/pages/Home.tsx
  front/src/pages/User.tsx
  front/src/pages/UserCart.tsx
  front/src/react-app-env.d.ts
  front/tsconfig.json
Labels: task

#54 resolve erros after pr
  api-server/src/main/java/org/gantry/apiserver/domain/Container.java
  api-server/src/main/java/org/gantry/apiserver/persistence/ContainerRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/ContainerService.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/main/resources/init/data.sql
  api-server/src/test/java/org/gantry/apiserver/domain/DockerClientConnectTest.java
  api-server/src/test/java/org/gantry/apiserver/service/ContainerServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
Labels: chores

#58 add duplicateStrategy
  api-server/build.gradle
  docker/Dockerfile
Labels: bug

#60 add Dockerfile for server
  docker/Dockerfile.server
Labels: chores

#56 add new apis
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTAuthenticationFilter.java
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTAuthorizationFilter.java
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTUtil.java
  api-server/src/main/java/org/gantry/apiserver/config/security/SecurityConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/domain/Authority.java
  api-server/src/main/java/org/gantry/apiserver/domain/User.java
  api-server/src/main/java/org/gantry/apiserver/exception/MismatchedPasswordException.java
  api-server/src/main/java/org/gantry/apiserver/exception/UserNotFoundException.java
  api-server/src/main/java/org/gantry/apiserver/persistence/UserRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/UserService.java
  api-server/src/main/java/org/gantry/apiserver/web/UserController.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/JoinRequest.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ResetPasswordRequest.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/UserResponse.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/UserTokenResponse.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/UserUpdateRequest.java
  api-server/src/test/java/org/gantry/apiserver/config/security/JWTUtilTest.java
  api-server/src/test/java/org/gantry/apiserver/config/security/SecurityConfigurationIntegrationTest.java
  api-server/src/test/java/org/gantry/apiserver/service/UserServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/web/UserControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/UserIntegrationTest.java
Labels: task

#65 Chores 059 server build
  bin/build-front.sh
  bin/deploy-front.sh
  bin/run-api-server.sh
  bin/run-front.sh
  bin/start.sh
  bin/test-front.sh
  docker/Dockerfile
  docker/Dockerfile.server
Labels: chores

#81 Update docker-publish.yml
  .github/workflows/docker-publish.yml
Labels: chores

#78 modify the code to make it accessible only by a admin user
  api-server/src/main/java/org/gantry/apiserver/web/UserController.java
  api-server/src/test/java/org/gantry/apiserver/web/UserIntegrationTest.java
Labels: feature

#80 Update Dockerfile
  docker/Dockerfile
Labels: chores

#84 ignore ex-tests
  front/package.json
  front/src/App.test.tsx
Labels: bug

#90 tester needs at least 1 test case
  front/src/App.test.tsx
Labels: bug

#86 add platform apis. create, update, activate, delete, get and list
  api-server/src/main/java/org/gantry/apiserver/config/security/SecurityConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/domain/Platform.java
  api-server/src/main/java/org/gantry/apiserver/exception/NoSuchPlatformException.java
  api-server/src/main/java/org/gantry/apiserver/exception/UserNotFoundException.java
  api-server/src/main/java/org/gantry/apiserver/persistence/PlatformRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/PlatformService.java
  api-server/src/main/java/org/gantry/apiserver/service/UserService.java
  api-server/src/main/java/org/gantry/apiserver/web/PlatformController.java
  api-server/src/main/java/org/gantry/apiserver/web/UserController.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/PlatformCreateRequest.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/PlatformResponse.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/PlatformUpdateRequest.java
  api-server/src/test/java/org/gantry/apiserver/web/PlatformIntegrationTest.java
Labels: task

#88 Front add signup page
  api-server/build.gradle
  api-server/src/main/java/org/gantry/apiserver/config/security/SecurityConfiguration.java
  front/src/App.tsx
  front/src/components/ApplicationList/ApplicationCat.tsx
  front/src/components/Modal.tsx
  front/src/pages/ApplicationDetail.tsx
  front/src/pages/Signup/Signup.tsx
  front/tsconfig.json
Labels: chores

#94 add Container Logs Method at Application Controller, Service
  api-server/build.gradle
  api-server/src/main/java/org/gantry/apiserver/config/WebSocketAuthInterceptor.java
  api-server/src/main/java/org/gantry/apiserver/config/WebSocketConfig.java
  api-server/src/main/java/org/gantry/apiserver/config/security/SecurityConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/domain/Container.java
  api-server/src/main/java/org/gantry/apiserver/domain/docker/ContainerLogHandler.java
  api-server/src/main/java/org/gantry/apiserver/domain/docker/DockerClientConnect.java
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/web/ApplicationController.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ApplicationResponse.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ContainerLogResponse.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ContainerResponse.java
  api-server/src/test/java/org/gantry/apiserver/domain/DockerClientTemplateConnectTest.java
  api-server/src/test/java/org/gantry/apiserver/domain/RealDockerTest.java
Labels: chores

#101 bugfix
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/service/ContainerService.java
  api-server/src/main/java/org/gantry/apiserver/web/ApplicationController.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/test/java/org/gantry/apiserver/domain/DockerClientTemplateConnectTest.java
  api-server/src/test/java/org/gantry/apiserver/domain/RealDockerTest.java
Labels: bug

#103 modify the function, log tailing
  api-server/src/main/java/org/gantry/apiserver/domain/docker/ContainerLogHandler.java
  api-server/src/main/java/org/gantry/apiserver/domain/docker/DockerClientConnect.java
  api-server/src/main/java/org/gantry/apiserver/exception/ThrowableConsumer.java
Labels: feature

#109 update
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/pages/LogIn.tsx
  front/tsconfig.json
Labels: chores

#105 Front, API Server 통합
  api-server/src/main/java/org/gantry/apiserver/config/security/JWTAuthorizationFilter.java
  api-server/src/main/java/org/gantry/apiserver/config/security/SecurityConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/exception/UserNotFoundException.java
  api-server/src/main/java/org/gantry/apiserver/service/ContainerService.java
  api-server/src/main/java/org/gantry/apiserver/service/UserService.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/main/java/org/gantry/apiserver/web/ControllerAdvisor.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ApplicationResponse.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ContainerLogResponse.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ErrorResponse.java
  front/src/App.tsx
  front/src/api/application.ts
  front/src/api/user.ts
  front/src/components/ApplicationList/ApplicationCat.tsx
  front/src/components/Navbar.tsx
  front/src/config/config.ts
  front/src/pages/ApplicationDetail.tsx
  front/src/pages/ApplicationsList.tsx
  front/src/pages/Home.tsx
  front/src/pages/LogIn.tsx
  front/tsconfig.json
Labels: chores

#112 bugfix- test failure
  api-server/src/main/java/org/gantry/apiserver/web/ControllerAdvisor.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ErrorResponse.java
Labels: bug

#122 환경변수를 Frontend에 반영할 수 있도록 수정
  README.md
  api-server/src/test/java/org/gantry/apiserver/config/security/SecurityConfigurationIntegrationTest.java
  bin/run-front.sh
  front/public/env.js
  front/public/index.html
  front/src/config/config.ts
  front/src/env.js
Labels: chores

#133 update
  README.md
  api-server/src/main/java/org/gantry/apiserver/domain/docker/DockerClientConnect.java
  bin/run-api-server.sh
Labels: chores

#134 Chores 132 enable to set application.properties
  README.md
  bin/run-api-server.sh
Labels: chores
