Repository gantry-project/gantry-docker, pull requests merged in 2023-03, with the labels that each got.

#14 Task 004 backend healthcheck api
  .gitignore
  api-server/build.gradle
  api-server/gradle/wrapper/gradle-wrapper.jar
  api-server/gradle/wrapper/gradle-wrapper.properties
  api-server/gradlew
  api-server/gradlew.bat
  api-server/settings.gradle
  api-server/src/main/java/org/gantry/apiserver/ApiServerApplication.java
  api-server/src/main/java/org/gantry/apiserver/domain/Application.java
  api-server/src/main/java/org/gantry/apiserver/domain/BaseTimeEntity.java
  api-server/src/main/java/org/gantry/apiserver/domain/ContainerInfo.java
  api-server/src/main/java/org/gantry/apiserver/domain/ContainerStatus.java
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClient.java
  api-server/src/main/java/org/gantry/apiserver/domain/PlatformType.java
  api-server/src/main/java/org/gantry/apiserver/exception/NoSuchApplicationException.java
  api-server/src/main/java/org/gantry/apiserver/persistence/ApplicationRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/web/ApplicationController.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/main/java/org/gantry/apiserver/web/ControllerAdvice.java
  api-server/src/main/java/org/gantry/apiserver/web/HealthCheckController.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ApplicationDto.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ContainerDto.java
  api-server/src/main/resources/application.properties
  api-server/src/test/java/org/gantry/apiserver/ApiServerApplicationTests.java
  api-server/src/test/java/org/gantry/apiserver/persistence/ApplicationRepositoryTest.java
  api-server/src/test/java/org/gantry/apiserver/service/ApplicationServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ApplicationControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/HealthCheckControllerTest.java
  bin/build-api-server.sh
  bin/deploy-api-server.sh
  bin/run-api-server.sh
  bin/test-api-server.sh
Labels: task

#23 react-router-dom
  front/package.json
  front/src/App.css
  front/src/App.tsx
  front/src/components/HomeMenu/HomeMenuCard.tsx
  front/src/components/Layout.tsx
  front/src/index.tsx
  front/src/pages/DockerList.tsx
  front/src/pages/Home.tsx
Labels: feature

#31 Front docker order page
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/components/Navbar.tsx
  front/src/components/UserProfile/UserOrder.tsx
  front/src/components/sidebar/index.tsx
  front/src/pages/User.tsx
  front/src/pages/UserCart.tsx
Labels: feature

#32 front-dockerList
  front/.gitignore
  front/eslintrc.js
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.test.tsx
  front/src/App.tsx
  front/src/components/DockerList/DockerCat.tsx
  front/src/components/DockerList/DockerItemCard.tsx
  front/src/components/DockerList/DockerListHeader.tsx
  front/src/components/Footer.tsx
  front/src/components/HomeMenu/HomeMenu.tsx
  front/src/components/HomeMenu/HomeMenuCard.tsx
  front/src/components/Layout.tsx
  front/src/components/Navbar.tsx
  front/src/components/Sidebar/SidebarItem/index.jsx
  front/src/components/Sidebar/SidebarItem/styles.js
  front/src/components/Sidebar/index.jsx
  front/src/components/Sidebar/styles.js
  front/src/components/UserProfile/UserOrder.tsx
  front/src/dummyData.js
  front/src/index.css
  front/src/index.tsx
  front/src/pages/DockerList.tsx
  front/src/pages/Home.tsx
  front/src/pages/User.tsx
  front/src/pages/UserCart.tsx
  front/src/react-app-env.d.ts
  front/src/reportWebVitals.ts
  front/src/setupTests.ts
  front/tsconfig.json
Labels: feature

#33 front-dockerListPage
  front/src/components/DockerList/DockerCat.tsx
  front/src/dummyData.js
  front/src/pages/DockerList.tsx
Labels: feature

#25 add DockerClient Dependency, change DockerClient -> DockerClientConne…
  api-server/build.gradle
  api-server/src/main/java/org/gantry/apiserver/config/DockerConfiguration.java
  api-server/src/main/java/org/gantry/apiserver/domain/Application.java
  api-server/src/main/java/org/gantry/apiserver/domain/Container.java
  api-server/src/main/java/org/gantry/apiserver/domain/ContainerInfo.java
  api-server/src/main/java/org/gantry/apiserver/domain/ContainerStatus.java
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClient.java
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClientConnect.java
  api-server/src/main/java/org/gantry/apiserver/persistence/ApplicationRepository.java
  api-server/src/main/java/org/gantry/apiserver/persistence/ContainerRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/web/ApplicationController.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ApplicationDto.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ContainerDto.java
  api-server/src/main/resources/application.properties
  api-server/src/test/java/org/gantry/apiserver/domain/DockerClientConnectTest.java
  api-server/src/test/java/org/gantry/apiserver/persistence/ApplicationRepositoryTest.java
  api-server/src/test/java/org/gantry/apiserver/service/ApplicationServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ApplicationControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
Labels: chores, feature

#35 resolve the broken test-cases
  api-server/build.gradle
  api-server/src/main/java/org/gantry/apiserver/domain/Application.java
  api-server/src/main/java/org/gantry/apiserver/domain/Container.java
  api-server/src/main/java/org/gantry/apiserver/domain/ContainerStatus.java
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClientConnect.java
  api-server/src/main/java/org/gantry/apiserver/persistence/ApplicationRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/web/ControllerAdvisor.java
  api-server/src/main/resources/application.properties
  api-server/src/test/java/org/gantry/apiserver/domain/DockerClientConnectTest.java
  api-server/src/test/java/org/gantry/apiserver/persistence/ApplicationRepositoryTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ApplicationControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
Labels: chores

#36 add new api for restart
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClientConnect.java
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/test/java/org/gantry/apiserver/domain/DockerClientConnectTest.java
  api-server/src/test/java/org/gantry/apiserver/service/ApplicationServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
Labels: feature

#37 add new api to running containers
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClientConnect.java
  api-server/src/main/java/org/gantry/apiserver/persistence/ContainerRepository.java
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/service/ContainerService.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/test/java/org/gantry/apiserver/service/ApplicationServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/service/ContainerServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
Labels: feature

#39 apply swagger
  api-server/build.gradle
  api-server/src/main/java/org/gantry/apiserver/config/OpenApiConfig.java
  api-server/src/main/java/org/gantry/apiserver/domain/Container.java
  api-server/src/main/java/org/gantry/apiserver/domain/DockerClientConnect.java
  api-server/src/main/java/org/gantry/apiserver/exception/NoSuchApplicationException.java
  api-server/src/main/java/org/gantry/apiserver/exception/NoSuchContainerException.java
  api-server/src/main/java/org/gantry/apiserver/service/ApplicationService.java
  api-server/src/main/java/org/gantry/apiserver/service/ContainerService.java
  api-server/src/main/java/org/gantry/apiserver/web/ApplicationController.java
  api-server/src/main/java/org/gantry/apiserver/web/ContainerController.java
  api-server/src/main/java/org/gantry/apiserver/web/ControllerAdvisor.java
  api-server/src/main/java/org/gantry/apiserver/web/HealthCheckController.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ApplicationRequest.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ContainerRequest.java
  api-server/src/main/java/org/gantry/apiserver/web/dto/ErrorResponse.java
  api-server/src/main/resources/application.properties
  api-server/src/test/java/org/gantry/apiserver/ApiServerApplicationTests.java
  api-server/src/test/java/org/gantry/apiserver/domain/DockerClientConnectTest.java
  api-server/src/test/java/org/gantry/apiserver/service/ApplicationServiceTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ApplicationControllerTest.java
  api-server/src/test/java/org/gantry/apiserver/web/ContainerControllerTest.java
Labels: task

#46 add detailPage
  api-server/src/main/java/org/gantry/apiserver/web/ApplicationController.java
  front/src/App.tsx
  front/src/components/DockerList/DockerCat.tsx
  front/src/components/Footer.tsx
  front/src/components/Layout.tsx
  front/src/pages/ContainerDetail.tsx
Labels: feature

#45 add init data for test
  api-server/src/main/resources/application.properties
  api-server/src/main/resources/init/data.sql
Labels: chores
